site_name: ХНЕУ ім. С Кузнеця
extra:
  generator: false
      
theme:
    name: material
    custom_dir: theme
    favicon:  assets/book-open-solid.svg
    logo: assets/logo-org.png
    locale: uk
    language: uk
    features:
      - navigation.expand
      - navigation.top
      - navigation.instant
      - navigation.tracking
    palette:
      - scheme: default
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/weather-night
          name: Switch to light mode
nav:
    - Титульна сторінка: 'index.md'
    - Вступ: '00_preface.md'
    - Зміст: '00_contents.md'
    - Форматування тексту: 'content01.md'
    - Блоки: 'content02.md'
    - Таблиці: 'content03.md'
    - Зоображення: 'content04.md'
    - Формули: 'content05.md'
    - Мультимедія та інтерактив: 'content06.md'
    - Особливі блоки: 'content07.md'
copyright: KHNUE &copy; 2009-2022 
plugins:
  - search
  - enumerate-headings:
      increment_across_pages: false
markdown_extensions:
    - toc:
        permalink: "#"
        slugify: !!python/name:pymdownx.slugs.uslugify
